apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
spec:
  type: NodePort
  selector:
    app: flaskapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Use a port in 30000-32767
